services:
  redis:
    image: redis
    ports:
      - 6379:6379

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_sekolah
      MYSQL_USER: root2
      MYSQL_PASSWORD: root2
    ports:
      - "3306:3306"
    volumes:
      - ./docker-dev-volumes/mysql_data:/var/lib/mysql
  app:
    tty: true
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - 2003:80
    command: bash -c "chown www-data:www-data -R /var/www/storage && composer update && apache2-foreground"
    volumes:
      - ./app:/var/www
      - ./app/public:/var/www/html

  app2:
    tty: true
    build:
      context: app2
      dockerfile: Dockerfile
    ports:
      - 2004:80
    command: bash -c "chown www-data:www-data -R /var/www/storage && composer update && apache2-foreground"
    volumes:
      - ./app2:/var/www
      - ./app2/public:/var/www/html